# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ea51ba072c3e7fd11027cce220736bb00d4965fe468e2b4608356df79e0c96eec795acdff9aef37fea55038996694b7b068e7e29a01a2a6e7f07441239956f

test:
  secret_key_base: 7173a5e57936056f678e0ffe8797fd8c67fe26b90add0cb069b51952cdf4c020bfabefe4b164d25f4ce448ce1f83e313bc6873d30e7d27954cbb51b3ead6d64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
